language: ruby

rvm:
  - jruby-19mode
  - 2.1.2
  - 1.9.3

gemfile:
  - ci/Gemfile.rails-4.1.x
  - ci/Gemfile.rails-4.0.x
  - ci/Gemfile.rails-3.2.x

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script: WITH_ADVISORY_LOCK_PREFIX=$TRAVIS_JOB_ID bundle exec rake --trace

before_script:
  - mysql -e 'create database with_advisory_lock_test'
  - psql -c 'create database with_advisory_lock_test' -U postgres

matrix:
  exclude:
